name: swarm-iha-project  # Docker Desktop'ta görünecek grup ismi burası

services:
  swarm-node:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swarm_container
    volumes:
      - ..:/home/swarm_user/workspace
    tty: true
    stdin_open: true